### ISSUE TITLE
Question about the calculation of bias b

### ISSUE THREAD

**Issue by LiLiu1118** [nihil21/custom-svm#3]
Hallo, i think the for loop around line 130 of svm.py use the total number of support vectors to calculate and average the value. But according to [https://www.microsoft.com/en-us/research/uploads/prod/2006/01/Bishop-Pattern-Recognition-and-Machine-Learning-2006.pdf](url) 7.37, we need to use the number of number of 0<lambda<C to average. I don't know if I am right, looking forward to your reply

**Comment by nihil21** [comment]
You're right, we didn't consider the "lambda < C" constraint in the computation of the bias; now it should be fixed.
Thanks for your remark!
